/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bgsubsconverter;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author pesho
 */
public class BGSubsConverter extends javax.swing.JFrame {

    /**
     * Creates new form EncodingConverter
     */
    public BGSubsConverter() {
        super("Конвертер от WINDOWS-1251 до UTF-8 за Линукс");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilenameFrom = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        lblFilenameTo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblChooseFileFrom = new javax.swing.JLabel();
        btnChooseFileFrom = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblChooseFileTo = new javax.swing.JLabel();
        btnChooseFileTo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConvert.setText("Преобразувай до UTF-8");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        lblChooseFileFrom.setText("Файл за четене:");

        btnChooseFileFrom.setText("Потърси");
        btnChooseFileFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblChooseFileFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnChooseFileFrom)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseFileFrom)
                    .addComponent(btnChooseFileFrom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblChooseFileTo.setText("Файл за записване:");

        btnChooseFileTo.setText("Потърси");
        btnChooseFileTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblChooseFileTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnChooseFileTo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseFileTo)
                    .addComponent(btnChooseFileTo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilenameFrom)
                    .addComponent(btnConvert)
                    .addComponent(lblFilenameTo)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFilenameFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFilenameTo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConvert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseFileFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileFromActionPerformed
        File file;
        JFileChooser jfc;
        int jfcState;
        
        jfc = new JFileChooser();
        jfcState = jfc.showOpenDialog(this);
        if(jfcState != JFileChooser.CANCEL_OPTION)
        {
            file = jfc.getSelectedFile();
            if(file.exists())
            {
                lblFilenameFrom.setText(file.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_btnChooseFileFromActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        Process p;
        BufferedReader reader;
        String line;
        StringBuilder sb;
        String[] stringArray;
        Runtime runtime;
        String command;
        
        if(lblFilenameFrom.getText().length() == 0 || lblFilenameTo.getText().length() == 0)
            return;
        
        runtime = Runtime.getRuntime();
        sb = new StringBuilder();
        
        try {
                p = runtime.exec(String.format("file -bi %s", lblFilenameFrom.getText()));
                p.waitFor();
                    
                reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
                line = "";
                while ((line = reader.readLine())!= null) {
                    sb.append(line);
                }
                stringArray = sb.toString().split(" ");

                if(stringArray[1].matches("charset=iso-8859-1"))
                {   
                    command = String.format("iconv -f WINDOWS-1251 -t UTF-8 %s > %s", lblFilenameFrom.getText(), lblFilenameTo.getText());
                    runtime.exec(new String[]{"sh", "-c", command.replace("(", "\\(").replace(")", "\\)")});  
                }else
                    JOptionPane.showMessageDialog(this, String.format("Файла за четене има друго кодиране:\n%s", stringArray[1]));
            } catch (IOException ex) {
                String errorMessage = ex.getMessage();
                JOptionPane.showMessageDialog(this, errorMessage);
                System.err.println(errorMessage);
                ex.printStackTrace();
            } catch (InterruptedException ex) {
                String errorMessage = ex.getMessage();
                JOptionPane.showMessageDialog(this, errorMessage);
                System.err.println(errorMessage);
                ex.printStackTrace();
            }
        lblFilenameFrom.setText("");
        lblFilenameTo.setText("");
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnChooseFileToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileToActionPerformed
        File file;
        JFileChooser jfc;
        int jfcState;
        
        jfc = new JFileChooser();
        jfcState = jfc.showSaveDialog(this);
        if(jfcState != JFileChooser.CANCEL_OPTION)
        {
            file = jfc.getSelectedFile();
            if(file.exists())
                JOptionPane.showMessageDialog(this, "Изберете друго име на файла за записване!");
            else
                lblFilenameTo.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnChooseFileToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BGSubsConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BGSubsConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BGSubsConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BGSubsConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BGSubsConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFileFrom;
    private javax.swing.JButton btnChooseFileTo;
    private javax.swing.JButton btnConvert;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChooseFileFrom;
    private javax.swing.JLabel lblChooseFileTo;
    private javax.swing.JLabel lblFilenameFrom;
    private javax.swing.JLabel lblFilenameTo;
    // End of variables declaration//GEN-END:variables
}
